version: '2.1'

networks:
  cscl-hooks-bridge:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: csclwebhook
    restart: always
    container_name: csclwebhook
    networks:
      - cscl-hooks-bridge
    volumes:
      - ./lib/web/templates:/usr/src/app/lib/web/templates
    ports:
      - 4000:4000
    links:
      - postgres
    environment:
      - PGSQL_DEV_DATABASE=csclservicesdev
      - PGSQL_DEV_USERNAME=postgres
      - PGSQL_DEV_PASSWORD=csclserviceswebhook
      - PGSQL_DEV_HOSTNAME=postgres
      - PGSQL_TEST_DATABASE=csclservicestst
      - PGSQL_TEST_USERNAME=postgres
      - PGSQL_TEST_PASSWORD=csclserviceswebhook
      - PGSQL_TEST_HOSTNAME=postgres
      - GITHUB_CLIENT_ID=XXXX
      - GITHUB_CLIENT_SECRET=XXXX
      - TWITTER_CONSUMER_KEY=XXXX
      - TWITTER_CONSUMER_SECRET=XXXX
  postgres:
    image: postgres:alpine
    restart: always
    networks:
      - cscl-hooks-bridge
    container_name: csclwebhook_db
    environment:
      - POSTGRES_PASSWORD=csclserviceswebhook
